version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: breizsport-web
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - breizsport-network

networks:
  breizsport-network:
    driver: bridge 